insert into public.games (
  id,
  played_at,
  platform,
  user_username,
  opponent_username,
  user_team,
  opponent_team,
  user_score,
  opponent_score,
  result,
  stadium,
  hitting_difficulty,
  pitching_difficulty,
  weather,
  attendance,
  user_game_score,
  opponent_game_score,
  raw_html_filename,
  is_public,
  coop_players
)
values (
  2603202401,
  '2026-03-18T22:15:00Z',
  'Crossplay',
  'AceCaptain',
  'RivalSlugger',
  'New York Yankees',
  'Los Angeles Dodgers',
  6,
  3,
  'W',
  'Laughing Mountain Park',
  'Hall of Fame',
  'Legend',
  'Clear',
  18244,
  87,
  71,
  'sample-show26-boxscore.html',
  true,
  array['AceCaptain', 'ClutchLefty']
)
on conflict (id) do nothing;
